### ISSUE TITLE
Move to CycleJS Community

### ISSUE THREAD

**Issue by TylorS** [vic/awesome-cyclejs#46]
Hello! 

We've just created a github organization for a place to organize community Cycle.js contributions and think this repository would be a great addition if you are willing :)

You, and all your contributors will of course have all the permissions you already have here

You can find us at https://github.com/cyclejs-community

**Comment by vic** [comment]
Hey, that's great, of course I'm willing to transfer this repo to the new org.

**Comment by TylorS** [comment]
Great! I'll send you an invite to the org momentarily :)

**Comment by TylorS** [comment]
Sent!

**Comment by vic** [comment]
Thanks. :)

**Comment by TylorS** [comment]
I made you an owner, please feel free to invite others as members
