### ISSUE TITLE
Some of the resources are moved and star counts outdated

### ISSUE THREAD

**Issue by olpeh** [vic/awesome-cyclejs#97]
This is an awesome list. However, some of the resources like Cycle.js examples are moved and the amount of stars do not match the actual amounts anymore. I think this is especially unwanted for create-cycle-app as it does not get enough visibility in this list at the moment. 

I suggest we do:
- Go through the list, update all the links that are outdated and/or missing
- Add missing resources to the list if there are some
- Update the amounts of stars or remove the star amounts from this list (???)

I volunteer for doing the manual work needed in order to fix this.

**Comment by artfuldev** [comment]
Hi @olpeh, thank you for the enthusiasm! And welcome to the community! 🎉 

You could just submit a pull request with the changes to the README file. Maybe we can start with a pull request that has updated stars, and take it from there. What do you think?

PS: Please go through the [contribution guidelines](https://github.com/cyclejs-community/awesome-cyclejs/blob/master/contributing.md)

**Comment by olpeh** [comment]
Yes, sounds good. I'll submit a PR soon(ish).
